---
- name: install lamp server
  hosts: webserver
  become: yes
  vars:
    info_page_path: /var/www/html/info.php
  tasks:
    - name: install apache
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
    - name: enable & restart
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: installing php packages
      ansible.builtin.package: 
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
      notify:
        - restart apache     
    - name: copy php package
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_page_path }}"
      notify:
        - restart apache  
  handlers: 
    - name: restart apache 
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        state: started

