---
- name: aws-cli
  hosts: all
  become: yes 
  tasks:
    - name: aws-cli install
      ansible.builtin.apt:
        name: awscli
        state: present
        update_cache: yes
    - name: copy sh file
      ansible.builtin.copy:
        src: r.sh
        dest: /home/devops 
        mode: '0755' 
    - name: shell
      ansible.builtin.shell: 
        cmd: r.sh 

    
