---
- name: install gol
  hosts: all
  become: yes
  tasks: 
    - name: install java-8 & tomcat9
      ansible.builtin.apt:
        name: 
          - openjdk-8-jdk
          - tomcat9
        state: latest
        update_cache: yes
    - name: download game of life
      ansible.builtin.get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
        dest: /tmp/gameoflife.war
    - name: copy 
      ansible.builtin.copy:
        src: /tmp/gameoflife.war
        dest: /var/lib/tomcat9/webapps/gameoflife.war
          
